# Generated by Django 4.2.20 on 2025-03-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=9, verbose_name="Telemóvel")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("quote", "Pedir Orçamento"),
                            ("question", "Esclarecer Dúvidas"),
                        ],
                        max_length=20,
                        verbose_name="Assunto",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Contacto",
                "verbose_name_plural": "Pedidos de Contacto",
            },
        ),
    ]
