# Generated by Django 4.2.20 on 2025-04-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="gdpr_consent",
            field=models.BooleanField(default=False, verbose_name="Consentimento GDPR"),
        ),
    ]
